package bordatech.io.sourcemfb.iso8583.enums;

import lombok.Getter;

@Getter
public enum MessageAction {
  AUTHORIZATION_REQUEST("0100"),
  AUTHORIZATION_RESPONSE("0110"),
  TRANSACTION_REQUEST("0200"),
  NETWORK_MGT_REQUEST("0800"),
  NETWORK_MGT_RESPONSE("0810"),
  TRANSACTION_COMPLETION("0202"),
  TRANSACTION_RESPONSE("0210"),
  TRANSACTION_COMPLETION_RESPONSE("0202"),
  REVERSAL_ADVICE("0420"),
  REVERSAL_ADVICE_REPEAT("0421"),
  REVERSAL_ADVICE_RESPONSE("0430"),
  TRANSACTION_ADVICE("0220"),
  TRANSACTION_ADVICE_REPEAT("0221"),
  TRANSACTION_ADVICE_RESPONSE("0230"),
  TRANSACTION_NOTIFICATION_ADVICE("9220"),
  TRANSACTION_NOTIFICATION_ADVICE_RESPONSE("9230");

  private String value;

  MessageAction(String value) {
    this.value = value;
  }

}
